// Application-wide constants
const DEFAULT_LOG_LEVEL = 'info';
const MAX_STRING_LENGTH = 1000;
const PRECISION = 10;
const DEFAULT_TIMEOUT = 5000;
const MAX_RETRY_ATTEMPTS = 3;
const MIN_NUMBER = -Number.MAX_SAFE_INTEGER;
const MAX_NUMBER = Number.MAX_SAFE_INTEGER;
const DEFAULT_CACHE_SIZE = 100;
const DEFAULT_API_VERSION = 'v1';

module.exports = {
  DEFAULT_LOG_LEVEL,
  MAX_STRING_LENGTH,
  PRECISION,
  DEFAULT_TIMEOUT,
  MAX_RETRY_ATTEMPTS,
  MIN_NUMBER,
  MAX_NUMBER,
  DEFAULT_CACHE_SIZE,
  DEFAULT_API_VERSION
};



